### PR TITLE
add splix

### PR DESCRIPTION
**Pull request by fmartinou**
Hello,

For my personal needs, I had to add Samsung printer drivers ([Splix](http://splix.ap2c.org/)).
Feel free to integrate if your interested.
Regards

### CODE REVIEW

**Comment by olbat** [comment]
I think that this package is already included in the image (because it's a dependency of the [printer-driver-all](https://packages.debian.org/stable/text/printer-driver-all) package).

Am I wrong?

**Comment by olbat** [comment]
I just did the test, it seems to be present in the image:
```
$ docker run --rm olbat/cupsd dpkg -l | grep splix
ii  printer-driver-splix              2.0.0+svn315-7               amd64        Driver for Samsung and Xerox SPL2 and SPLc laser printers
```
Did encounter problems to use your Samsung printer without your patch?

**Comment by fmartinou** [comment]
You're right, the dependency is present (and the driver I need too). 
I think I did a mishmash between several CUPS Docker image I have tried...
Sorry for the inconvenience.
I close the PR.

**Comment by olbat** [comment]
No problem, I'm happy this image can help you!

**Pull request closed without merging**
